# Generated by Django 3.0.6 on 2020-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=5000000)),
                ('video_link', models.CharField(max_length=200)),
                ('template_link', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(to='fwp.Category')),
            ],
        ),
    ]
