# Generated by Django 3.0.6 on 2020-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0002_auto_20200522_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='video_link',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='game',
            name='image_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
