# Generated by Django 3.0.6 on 2020-05-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0005_auto_20200522_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
