# Generated by Django 3.0.6 on 2020-05-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0007_auto_20200523_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='template_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tutorial_video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
