# Generated by Django 3.0.6 on 2020-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0008_auto_20200523_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='body',
            field=models.TextField(),
        ),
    ]
