# Generated by Django 3.0.6 on 2020-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0009_auto_20200523_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('game_name', models.CharField(max_length=200)),
            ],
        ),
    ]
