# Generated by Django 3.0.6 on 2020-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0010_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='game_name',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='user',
            new_name='your_name',
        ),
    ]
