# Generated by Django 3.0.6 on 2020-05-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0011_auto_20200523_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
