# Generated by Django 3.0.6 on 2020-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0012_auto_20200523_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_views',
            field=models.IntegerField(default=0),
        ),
    ]
