# Generated by Django 3.0.6 on 2021-05-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0013_game_user_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
