# Generated by Django 3.0.6 on 2021-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0014_auto_20210505_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
