# Generated by Django 4.2.2 on 2023-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwp', '0016_auto_20210505_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='body',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
